# -*- coding: utf-8 -*-
"""Copy of HW3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sRd6U6KOdtffKfSHzDCPiymmYL0p78D2

**Q1**. Please read WorldCupMatches.csv to a data frame to proceed
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import drive
import pandas as pd
drive.mount('/content/drive')
wc = pd.read_csv('/content/drive/MyDrive/DATA/WorldCupMatches.csv')

"""**Q2** Using seaborn's displot draw density curves to show the distributions of Home Team Goals for every year. """

sns.displot(wc, x="Home Team Goals", kind="kde", hue="Year")

"""**Q3** Draw violin plots to summarize Home Team Goals distributions for each year by using seaborn. Notice that labels are really clutterd. Then please refer to the earlier notebooks to have labels to appear on only select years which end with 0. You can use ax handle to call ax.set_xticklables(labels) for the labels your prepared."""

labels = [y if y%10==0 else None for y in list(wc.Year.unique())]

ax = sns.violinplot(data=wc, x='Year', y='Home Team Goals')
ax.set_xticklabels(labels)

"""**Q4** Please install joypy. Then visualize distributions for Home Team Goals and Away Team Goals' for each year. Once you visualize, please add  plt.style.use('seaborn-white') to see how colors change in your second run. Please also add the legend which you can find from the function prototype.


"""

!pip install joypy

import joypy as jp
import matplotlib

jp.joyplot(data=wc, column=['Home Team Goals', 'Away Team Goals'], by='Year', legend=True)
plt.style.use('seaborn-white')

"""**Q5** Please use groupby function on Home Team Initials to see the sum of Home Team Goals which can be saved to another data frame by adding .reset_index() end the end of your line. 

Then use your new data frame to visualize those total Home Team Goals for your top 5 countries (You can use Home Team Initials). You can use use df.sort_values() function on your data frame by tweaking the ascending option.

Notice that your x-axis will be having country initials, and y-axis will show the total number of Home Team Goals. 


"""

goals = wc.groupby(['Home Team Initials'])['Home Team Goals'].count().reset_index()

top = goals.sort_values(["Home Team Initials"], accending=True)

ax = top[0:5].plot.bar(x='Home Team Initials', y='Home Team Goals', rot=0)

"""**Q6** Please extract the rows for your top 4 countries (Home Team Initials') with the help of the previous question's answer. Then use joyplot again to visualize densities for 'Home Team Goals' and	'Away Team Goals' on the horizantal axis. Notice that your y-axis labels will be your country initials (Home Team Initials'). Make sure that your legend is visible and use 'dark_background' by calling plt.style.use again.


"""

plt.style.use('dark_background')

jp.joyplot(data=wc[10:15], column=['Home Team Goals', 'Away Team Goals'], by='Home Team Initials', ylim='own', legend=True)

"""**Q7** Please install seaborn_qqplot as shown below. Then draw a qqplot to compare probability distributions of Home Team Goals and Away Team Goals. Please comment on your finding. Do you think their distributions agree with each other? Please justify your answer by explaining the figure you obtained."""

!pip install seaborn_qqplot

from seaborn_qqplot import pplot #seaborn-qqplot is a seaborn extension adding qqplots.
plt.style.use('ggplot') #this is to change the color theme. 
pplot(wc, x='Home Team Goals', y='Away Team Goals', kind='qq', display_kws={"identity":True}, height=4, aspect=2)